### ISSUE TITLE
Add slither to GHA when this repository is made public

### ISSUE THREAD

**Issue by zajck** [fermionprotocol/contracts#3]
Slither can work on a private repository, but SARIF cannot be uploaded if the repository is private.
Once this repository is made public, add the following config to `ci.yaml`

```
 analyze:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Slither analyzer
        uses: crytic/slither-action@v0.3.2
        id: slither
        with:
          node-version: 20
          sarif: results.sarif
          fail-on: none
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

```
